/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Suikoden II)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800D48B0u
#define func_800D48B0 BootEntry  /* alias */
